# Generated by Django 6.0 on 2025-12-09 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_order', models.CharField(max_length=20, unique=True)),
                ('judul_buku', models.CharField(max_length=255)),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('status_global', models.CharField(choices=[('BARU', 'Order Baru'), ('PROSES', 'Dalam Pengerjaan'), ('SIAP', 'Siap Diambil/Dikirim'), ('BATAL', 'Dibatalkan')], default='BARU', max_length=10)),
                ('total_harga', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BookSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukuran_buku', models.CharField(max_length=50)),
                ('jenis_sampul', models.CharField(choices=[('SOFT', 'Softcover'), ('HARD', 'Hardcover')], max_length=50)),
                ('laminasi', models.CharField(choices=[('DOFF', 'Doff'), ('GLOSSY', 'Glossy')], max_length=50)),
                ('catatan_teknis', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spesifikasi', to='core_production.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_layout', models.CharField(choices=[('PENDING', 'Menunggu'), ('PROSES', 'Sedang Dikerjakan'), ('ACC', 'Final / ACC')], default='PENDING', max_length=10)),
                ('status_desain', models.CharField(choices=[('PENDING', 'Menunggu'), ('PROSES', 'Sedang Dikerjakan'), ('ACC', 'Final / ACC')], default='PENDING', max_length=10)),
                ('status_cetak', models.CharField(choices=[('ANTRI', 'Dalam Antrian'), ('PROSES', 'Sedang Dikerjakan'), ('SELESAI', 'Selesai')], default='ANTRI', max_length=10)),
                ('status_binding', models.CharField(choices=[('ANTRI', 'Dalam Antrian'), ('PROSES', 'Sedang Dikerjakan'), ('SELESAI', 'Selesai')], default='ANTRI', max_length=10)),
                ('status_finishing', models.CharField(choices=[('ANTRI', 'Dalam Antrian'), ('PROSES', 'Sedang Dikerjakan'), ('SELESAI', 'Selesai')], default='ANTRI', max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='core_production.order')),
            ],
        ),
    ]
