# Generated by Django 6.0 on 2025-12-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionworkflow',
            name='file_cover_final',
            field=models.FileField(blank=True, null=True, upload_to='uploads/cover/'),
        ),
        migrations.AddField(
            model_name='productionworkflow',
            name='file_layout_final',
            field=models.FileField(blank=True, null=True, upload_to='uploads/layout/'),
        ),
    ]
