# Generated by Django 6.0 on 2025-12-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_production', '0002_productionworkflow_file_cover_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookspecification',
            name='catatan_teknis',
            field=models.TextField(blank=True, help_text='Instruksi khusus untuk produksi'),
        ),
        migrations.AlterField(
            model_name='bookspecification',
            name='jenis_sampul',
            field=models.CharField(choices=[('SOFT', 'Softcover'), ('HARD', 'Hardcover')], default='SOFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookspecification',
            name='laminasi',
            field=models.CharField(choices=[('DOFF', 'Doff'), ('GLOSSY', 'Glossy')], default='DOFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookspecification',
            name='ukuran_buku',
            field=models.CharField(choices=[('A5', 'A5 (14.8 x 21 cm) - Standar Buku Ajar/Novel'), ('B5', 'B5 (17.6 x 25 cm) - Akademik/Jurnal'), ('A4', 'A4 (21 x 29.7 cm) - Majalah/Modul'), ('13x19', '13 x 19 cm - Novel Komersial/Fiksi'), ('14x20', '14 x 20 cm - Standar Umum'), ('15x23', '15.5 x 23 cm - Standar UNESCO'), ('CUSTOM', 'Custom / Ukuran Khusus')], default='A5', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='nomor_order',
            field=models.CharField(help_text='Contoh: PO-001', max_length=20, unique=True),
        ),
    ]
