# Generated by Django 6.0 on 2025-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_production', '0005_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jumlah_bayar',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total uang yang sudah diterima', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='status_pembayaran',
            field=models.CharField(choices=[('BELUM', '❌ Belum Bayar'), ('DP', '⚠️ Down Payment (DP)'), ('LUNAS', '✅ Lunas')], default='BELUM', max_length=10),
        ),
    ]
